version: "3"
services:
  in-memory-db:
    container_name: in-memory-db
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3066:3066
    volumes: 
      - in-memory-db:/app/data
    command: [ "npm", "t" ]
volumes:
  in-memory-db:
    driver: local
    driver_opts:
      type: none
      device: /data
      o: bind
